Assets/MediaPipe/SDK/Scripts/PInvoke/SafeNativeMethods.cs, Assets/MediaPipe/SDK/Scripts/PInvoke/UnsafeNativeMethods.cs
It wasn't possible to run editor while selected mobile platform (ex. android), due to wrong pre-processor directives in dll pickers
=> Made it possible to run editor while on iOS/Android platform target

WORKSPACE
Changed url and prefix for c++ rules to reflect renaming of branch as seen here: https://github.com/bazelbuild/rules_cc/issues/107
fixes #210
=> Updated WORKSPACE file

WORKSPACE
Modified WORKSPACE file to fix issues when using android library when building with Docker.
Linked issues/comments describing in more detail:
https://github.com/google/mediapipe/issues/1224#issuecomment-745190852
https://github.com/homuler/MediaPipeUnityPlugin/issues/269
=> "api_level = 21," added to WORKSPACE file in NDK configuration

Assets/Mediapipe/Samples/Common/Scripts/Solution.cs, Assets/Mediapipe/Samples/Scenes/Box Tracking/BoxTrackingSolution.cs, Assets/Mediapipe/Samples/Scenes/Face Detection/FaceDetectionSolution.cs, Assets/Mediapipe/Samples/Scenes/Face Mesh/FaceMeshSolution.cs, Assets/Mediapipe/Samples/Scenes/Hair Segmentation/HairSegmentationSolution.cs, Assets/Mediapipe/Samples/Scenes/Hand Tracking/HandTrackingSolution.cs, Assets/Mediapipe/Samples/Scenes/Holistic/HolisticTrackingSolution.cs, Assets/Mediapipe/Samples/Scenes/Instant Motion Tracking/InstantMotionTrackingSolution.cs, Assets/Mediapipe/Samples/Scenes/Iris Tracking/IrisTrackingSolution.cs, Assets/Mediapipe/Samples/Scenes/Object Detection/ObjectDetectionSolution.cs, Assets/Mediapipe/Samples/Scenes/Objectron/ObjectronSolution.cs, Assets/Mediapipe/Samples/Scenes/Pose Tracking/PoseTrackingSolution.cs
fix #302 
As described at https://github.com/homuler/MediaPipeUnityPlugin/issues/302#issuecomment-961018299, the camera image can advance while the main thread is being blocked in synchronous mode.
By this change, the camera image will be copied to the screen on CPU when running in synchronous mode.
=> fix: synchronize the input image and the output annotation

README.md, WORKSPACE, third_party/mediapipe_workaround.diff, third_party/opencv.BUILD, third_party/opencv_windows.BUILD
related to #331
- enable us to build native libraries on m1 mac
- upgrade OpenCV (we cannot build 3.4.10 on m1 mac)
=> build: support M1 Mac

README.md
I think the default OpenCV version for Windows is set according to opencv_windows.BUILD file https://github.com/homuler/MediaPipeUnityPlugin/blob/b3d122f65ce15e2c144ef1cacbf1e2fd62ef530e/third_party/opencv_windows.BUILD#L22
The line was changed from 3.4.10 to 3.4.16 in #366 and part of the README.md file is already updated https://github.com/homuler/MediaPipeUnityPlugin/blob/bed2f478eddf3b8be106adcc2044e576e8337e22/README.md#L422
=> doc: update default OpenCV version for Windows

Packages/com.github.homuler.mediapipe/Runtime/Scripts/Gpu/GlTextureBuffer.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Port/StatusTest.cs
Closes #415.
I'm unsure about that last check though. Was that intentional or genuine miss?
=> Fix minor mishaps

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/build-installation-issue.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/ISSUE_TEMPLATE/other-issue.yml
This PR upgrades the current issue templates to issue forms. All the current templates now have a corresponding form. This was created as suggested in #405.
You can check out the forms [here](https://github.com/Thomas-Boi/MediaPipeUnityPlugin/issues/new/choose). Choose the options that ends with `Form` to see the forms. 
Any changes/suggestions/questions are welcomed. Before merging, let me know and I can delete the old template files as well.
=> Add issue forms

build.py
=> fix: OpenCV installation path is incorrect

Packages/com.github.homuler.mediapipe/Runtime/Scripts/External/SerializedProto.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/External/SerializedProtoVector.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/PInvoke/NativeMethods/External/Protobuf_Unsafe.cs, mediapipe_api/external/protobuf.cc, mediapipe_api/external/protobuf.h
fix #457 
- make `SerializedProto` and `SerializedProtoVector` readonly
- hide memory addresses from users
- free proto's byte array when freeing `SerializedProtoVector`
=> fix: SerializedProto's memory leaks

docker/linux/x86_64/Dockerfile
fix #456
When the base image is cached, the `docker build` command can fail even with the `--no-cache` option.
=> build: update archlinux-keyring first when building a Docker image

build.py
Currently `PYTHON_BIN_PATH` must be set to build the plugin.
However, we can determine the `python` executable path at runtime because the `build.py` script is run by `python`.
And I don't come up with any reason why we would need to specify a different Python than the running one, I'll eliminate the need to specify `PYTHON_BIN_PATH` by this PR.
=> build: set sys.executable to PYTHON_BIN_PATH

docker/linux/x86_64/Dockerfile
Expand `UID_MAX` and `GID_MAX` to support `systemd-homed.service`.
=> build: expand UID_MAX and GID_MAX for systemd-homed.service

Assets/Mediapipe/Samples/Common/Scripts/ImageSourceSolution.cs, Assets/Mediapipe/Samples/Scenes/Box Tracking/BoxTrackingSolution.cs, Assets/Mediapipe/Samples/Scenes/Face Detection/FaceDetectionSolution.cs, Assets/Mediapipe/Samples/Scenes/Face Mesh/FaceMeshSolution.cs, Assets/Mediapipe/Samples/Scenes/Hair Segmentation/HairSegmentationSolution.cs, Assets/Mediapipe/Samples/Scenes/Hand Tracking/HandTrackingSolution.cs, Assets/Mediapipe/Samples/Scenes/Holistic/HolisticTrackingSolution.cs, Assets/Mediapipe/Samples/Scenes/Instant Motion Tracking/InstantMotionTrackingSolution.cs, Assets/Mediapipe/Samples/Scenes/Iris Tracking/IrisTrackingSolution.cs, Assets/Mediapipe/Samples/Scenes/MediaPipe Video/MediaPipeVideoSolution.cs, Assets/Mediapipe/Samples/Scenes/Object Detection/ObjectDetectionSolution.cs, Assets/Mediapipe/Samples/Scenes/Objectron/ObjectronSolution.cs, Assets/Mediapipe/Samples/Scenes/Pose Tracking/PoseTrackingSolution.cs
related to #428, #471 
This PR makes sample scenes run faster in synchronous mode.
With this change, one frame will be consumed to run the `CalculatorGraph`, which means that if the sample app runs at 60FPS and the `CalculatorGraph` runs faster than 60FPS, the main thread won't be blocked even in sync mode.
The downside is that the performance of the Non-Blocking sync mode, which should allow the sample app to run faster in theory,  will be degraded in some cases.
However, in environments where the sample app runs faster than 60FPS, this mode will still be superior.
=> perf(sample): make sample scenes run faster in sync mode

Assets/Mediapipe/Samples/Common/Scripts/ImageSource/TextureFrame.cs
fix #392 
`Texture#GetNativeTexturePtr` may not return on M1 Mac (cf. https://forum.unity.com/threads/texture-getnativetextureptr-may-not-return-on-m1-mac.1258506/).
This PR defers the calling of this method until it's necessary.
=> fix(sample): GetNativeTexturePtr may never return on M1 Mac

Assets/Mediapipe/Samples/Scenes/Instant Motion Tracking/InstantMotionTrackingSolution.cs
The anchor position in the Instant Motion Tracking Scene is flipped.
=> fix(sample): Anchor position is flipped

Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/FloatArrayPacket.cs
fix a bug introduced by #509.
I forgot to commit a change.
=> fix: FloatArrayPacket#At throws an exception

Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Formats/ImageFrame.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/GpuBufferPacket.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Gpu/GlCalculatorHelper.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Gpu/GlSyncPoint.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Gpu/GlTextureBuffer.cs
fix #514 
This bug is introduced by #509
=> fix(plugin): fail to initialize GlSyncPoint

Assets/Mediapipe/Samples/Scenes/Hair Segmentation/HairSegmentationGraph.cs
The orientation of the hair mask is wrong when running in synchronous mode.
=> fix: ignore ImageSource#isVerticallyFlipped in synchronous mode

Assets/Mediapipe/Samples/Common/Scripts/Bootstrap.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/External/Protobuf.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/PInvoke/NativeMethods/External/Protobuf_Unsafe.cs, mediapipe_api/external/protobuf.cc, mediapipe_api/external/protobuf.h
Set Protobuf's `LogHandler`.
Now if `libprotobuf` fails to parse a text, it can output the error message in the Console Window instead of stderr.
=> feat: set Protobuf LogHandler

Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/CalculatorGraph.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/CalculatorGraphConfigExtension.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/CalculatorGraphConfigExtension.cs.meta, Packages/com.github.homuler.mediapipe/Runtime/Scripts/PInvoke/NativeMethods/Framework/CalculatorGraph_Unsafe.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Extension/CalculatorGraphConfigExtension.cs, mediapipe_api/framework/calculator_graph.cc, mediapipe_api/framework/calculator_graph.h
`CalculatorGraph(string)` cannot initialize an instance if the given config format is invalid, but does not throw currently.
When some instance method is invoked after, it will trigger `SIGSEGV` and crash the whole application.
=> fix: constructor should throw if it fails to initialize

build.py
close #281 
- pass startup options to Bazel
- pass arbitrary build options to Bazel
- disable bitcode when `--no-apple_bitcode` is passed
=> build: allow arbitrary options to be passed to Bazel

Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/GlobalInstanceTable.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/OutputStream.cs
Fix a bug introduced by #563.
All the removing items must be enumerated before.
=> fix: Enumerator can be invalid when an item is deleted

Assets/MediaPipeUnity/Samples/Scenes/Instant Motion Tracking/Anchor3dAnnotation.cs, Assets/MediaPipeUnity/Samples/Scenes/Instant Motion Tracking/InstantMotionTrackingSolution.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/DetectionAnnotation.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/HierarchicalAnnotation.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/IrisLandmarkListAnnotation.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/PointAnnotation.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/RectangleAnnotation.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/RectangleListAnnotation.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/TransformAnnotation.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/CoordinateSystem/CameraCoordinate.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/CoordinateSystem/ImageCoordinate.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/CoordinateSystem/RealWorldCoordinate.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Unity/CoordinateSystem/ImageCoordinateTest.cs
Rename coordinate transform methods and add some missing helper methods.
- `ImageCoordinateSystem.GetLocalPosition` -> `ImageCoordinateSystem.ImageToLocalPoint`
- `RealWorldCoordinateSystem.GetLocalPosition` -> `RealWorldCoordinateSystem.RealWorldToLocalPoint`
- `CameraCoordinateSystem.GetLocalPosition` -> `CameraCoordinateSystem.CameraToLocalPoint`
- Add `CameraCoordinateSystem.GetApproximateQuaternion`
=> refactor!: coordinate transform and other helper methods

Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Port/Status.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Port/StatusTest.cs
Currently, there are only 2 Status factory methods, `Status.Ok` and `Status.FailedPrecondition`.
This PR adds missing factory methods such as `Status.InvalidArgument`.
=> feat(plugin): add missing Status factory methods

Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/CalculatorGraph.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Port/Status.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Gpu/GlCalculatorHelper.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/PInvoke/UnsafeNativeMethods.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/OutputStream.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Gpu/GlCalculatorHelperTest.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Gpu/GlContextTest.cs, mediapipe_api/common.cc, mediapipe_api/common.h, mediapipe_api/external/absl/status.h, mediapipe_api/framework/calculator_graph.cc, mediapipe_api/framework/calculator_graph.h, mediapipe_api/gpu/gl_calculator_helper.cc, mediapipe_api/gpu/gl_calculator_helper.h
fix #417
#417 seemed to occur because `NativePacketCallback` returns a pointer to a resource that is managed by the Managed Code, but its lifetime is only known to the Unmanaged Code.
#563 resolved it by pinning the resource for a while, but it's still unclear how long it should be pinned.
This PR allows the returned resource to be explicitly released by the Unmanaged Code, which will completely solve the issue.
=> refactor!: callback functions return StatusArgs instead of Status

Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/CalculatorGraphTest.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Format/ImageFrameTest.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Packet/BoolPacketTest.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Packet/FloatArrayPacketTest.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Packet/FloatPacketTest.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Packet/ImageFramePacketTest.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Packet/PacketTest.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Packet/SidePacketTest.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Packet/StringPacketTest.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Port/StatusOrGpuResourcesTest.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Port/StatusOrImageFrameTest.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Port/StatusOrStringTest.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Port/StatusTest.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/TimestampTest.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Tool/NameUtilTest.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Tool/ValidateNameTest.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/ValidatedGraphConfigTest.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Gpu/GlCalculatorHelperTest.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Gpu/GlContextTest.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Gpu/GlTextureTest.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Gpu/GpuResourcesTest.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/GpuOnlyAttribute.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/SignalAbortAttribute.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Unity/CoordinateSystem/ImageCoordinateTest.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Unity/Extension/ImageFrameExtensionTest.cs
The `expected` and `actual` arguments of `Assert.AreEqual` are interchanged, so this PR changes them back.
`namespace` of `Tests.dll` will also be changed.
=> chore: interchange the expected and actual arguments of Assert.AreEqual

.bazelrc, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Gpu/GpuBuffer.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/PInvoke/NativeMethods/Gpu/GpuBuffer_Safe.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Protobuf/Calculators/Tensorflow.meta, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Protobuf/Util/LabelMap.cs.meta, README.md, WORKSPACE, mediapipe_api/calculators/util/BUILD, mediapipe_api/gpu/gpu_buffer.cc, mediapipe_api/gpu/gpu_buffer.h, mediapipe_api/modules/iris_landmark/BUILD, mediapipe_api/util/BUILD, third_party/mediapipe_emscripten_patch.diff, third_party/mediapipe_extension.diff, third_party/mediapipe_model_path.diff, third_party/mediapipe_visibility.diff, third_party/mediapipe_workaround.diff, third_party/tensorflow_xnnpack_emscripten_fixes.diff
- Upgrade the MediaPipe version to v0.8.10
- remove `GpuBuffer#GetGlTextureBuffer`
- Disable WASM-related patches temporarily
=> feat(plugin): mediapipe v0.8.10

docker/windows/x86_64/Dockerfile
Currently, `docker build` freezes when running the `pacman` command.
I confirmed that the command described in [the official MSYS2 document](https://www.msys2.org/docs/ci/#docker) did not freeze, so replace the old command with the new one (using PowerShell).
=> fix: docker freezes when building a Docker Windows image

Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/ValidatedGraphConfigTest.cs
Currently, some tests that are not labeled `GpuOnly` can fail when the library was built with GPU disabled.
This PR fixes those test cases.
=> test: run tests with GPU disabled

Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/HolisticLandmarkListAnnotationController.cs
Holistic landmarks are being drawn twice right now.
SyncNow() is already called in DrawNow() right in front of it.
=> fix: avoid drawing holistic landmarks twice

.github/workflows/linux-test.yml, .github/workflows/macos-test.yml, .github/workflows/package.yml, .github/workflows/windows-test.yml
- Upgrade actions/cache to v3 to suppress deprecation warnings
- Upgrade actions/delete-artifact to v2 to suppress deprecation warnings
- Stop caching C:\_bzl
- it takes about 30 mins to upload the whole cache
- at least, we need to find a way to force CMake to skip building OpenCV when there's a cache
=> chore: upgrade Node.js 12 actions

Packages/com.github.homuler.mediapipe/Runtime/Scripts/PInvoke/NativeMethods/Util/ResourceUtil_Safe.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/ResourceManager/AssetBundleResourceManager.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/ResourceManager/LocalResourceManager.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/ResourceManager/StreamingAssetsResourceManager.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Util/ResourceManager.cs
- hide the `StdString` implementation from developers
- When extending the `ResourceManager`, we don't need to add `AOT.MonoCallback` attributes to some methods anymore.
This PR will change the `ResourceManager.ResourceProvider` I/F so it is a breaking change.
related to #830
=> refactor!: make ResourceManager more customizable

.github/workflows/package.yml
`Release Packages` workflow is failing, so remove some unused files to free up space.
https://github.com/homuler/MediaPipeUnityPlugin/actions/runs/4323932116
=> ci: free up space to avoid "No space left on device" error

Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Experimental/TextureFrame.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Experimental/TextureFramePool.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Util/GlobalInstanceTable.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Util.meta, Packages/com.github.homuler.mediapipe/Tests/EditMode/Util/GlobalInstanceTableTest.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Util/GlobalInstanceTableTest.cs.meta
When a `TextureFrame` is disposed, it is not GCed instantly, so the reference exists for a while.
It can be a problem because GlobalInstanceTable cannot remove such an instance, so this PR fixes it.
=> fix: dispose TextureFrame references instantly

.github/workflows/linux-test.yml, .github/workflows/macos-test.yml, .github/workflows/package.yml, .github/workflows/windows-test.yml
Currently, it takes more than 1 hour to test on Windows.
This PR aims to reduce the time taken by CI by caching the built libraries.
=> ci: cache built libraries for test

Assets/MediaPipeUnity/Samples/Common/Scripts/AssetLoader.cs, Assets/MediaPipeUnity/Samples/Common/Scripts/Bootstrap.cs, Assets/MediaPipeUnity/Samples/Common/Scripts/GraphRunner.cs, Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/TextureFrame.cs, Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/TextureFramePool.cs, Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/WebCamSource.cs, Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSourceSolution.cs, Assets/MediaPipeUnity/Samples/Scenes/AppSettings.asset, Assets/MediaPipeUnity/Samples/Scenes/Face Detection/FaceDetectionGraph.cs, Assets/MediaPipeUnity/Samples/Scenes/Face Mesh/FaceMeshGraph.cs, Assets/MediaPipeUnity/Samples/Scenes/Hair Segmentation/HairSegmentationGraph.cs, Assets/MediaPipeUnity/Samples/Scenes/Hand Tracking/HandTrackingGraph.cs, Assets/MediaPipeUnity/Samples/Scenes/Holistic/HolisticTrackingGraph.cs, Assets/MediaPipeUnity/Samples/Scenes/Pose Tracking/PoseTrackingGraph.cs, Assets/MediaPipeUnity/Samples/Scenes/Selfie Segmentation/SelfieSegmentationGraph.cs, Assets/MediaPipeUnity/Samples/Scenes/Tasks/Face Detection/FaceDetectorRunner.cs, Assets/MediaPipeUnity/Samples/Scenes/Tasks/Face Landmark Detection/FaceLandmarkerRunner.cs, Assets/MediaPipeUnity/Samples/Scenes/Tasks/Hand Landmark Detection/HandLandmarkerRunner.cs, README.md
- call Debug.Log in the sample app
- make Bootstrap error messages more suggestive
=> refactor(sample): more kind logging in the sample app

Assets/MediaPipeUnity/Samples/UI/Scripts/AutoFit.cs
If the camera is rotated, for example, by the Z axis, the size of the image is incorrectly adjusted because we are taking the global rotation of an image in `GetBoundingBoxSize(...)`. This effect is very noticeable when using a camera image from ARCoreCamera and applying it to RawImage in Canvas.
=> Fix: proper size for an image using AutoFit if camera is rotated

Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/WebCamSource.cs
After the `webCamDevice` is selected, it is always reset to the first `WebCamTexture.devices` when `Play()` is called.
introduced by #1017.
=> fix: switch between the back camera and front camera

Packages/com.github.homuler.mediapipe/Runtime/Scripts/External/StructArray.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/External/StructArray.cs.meta, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet.cs.meta, Packages/com.github.homuler.mediapipe/Runtime/Scripts/PInvoke/NativeMethods/Framework/Packet_Safe.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/PInvoke/NativeMethods/Framework/Packet_Unsafe.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Packet/PacketTest.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/PacketTest.cs, Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/PacketTest.cs.meta, mediapipe_api/framework/packet.cc, mediapipe_api/framework/packet.h
Migrating from generic Packet class to non-generic Packet class.
The non-generic Packet class will implement `packet_creator` and `packet_getter` APIs.
cf. https://developers.google.com/mediapipe/api/solutions/python/mp/packet_creator, https://developers.google.com/mediapipe/api/solutions/python/mp/packet_getter
=> feat: implement non-generic Packet class (bool/bool vector)

Assets/MediaPipeUnity/Samples/Common/Scripts/RunningMode.cs
Drop non-blocking sync mode, since the current sync mode doesn't block the main thread thanks to the new `OutputStream.WaitNextSync` API.
=> feat(sample): drop non-blocking sync mode

.bazelrc, .github/workflows/build-package.yml, .github/workflows/package.yml, build.py
`--fat_apk_cpu` option is not working as intended (e.g. `-march` option is decided only by `--cpu`) so remove the `fat` option temporarily.
=> build: remove the fat option and add x86/x86_64 options for android

Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/PacketGetterExtension.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/PoseLandmarkerResultAnnotationController.cs, mediapipe_api/framework/formats/image.cc
=> fix: dispose native resources of segmentation masks properly

.github/workflows/release-packages.yml
The release packages workflow is failing.
https://github.com/homuler/MediaPipeUnityPlugin/actions/runs/8295012077/job/22701159041
This PR will fix it.
=> ci: build the aar for arm64 only

Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/FaceLandmarkListWithIrisAnnotation.cs
I found and resolved "NullReferenceException" error in FaceMeshSolution under the following circumstances:
1) When Max Num Faces is greater than 2.
2) When there are multiple faces initially recognized but the count drops to just one.
=> Fix : multiple face landmark issue

Assets/MediaPipeUnity/Samples/Scenes/Tasks/Pose Landmark Detection/PoseLandmarkerRunner.cs
As a workaround for #1196, stop rotating the input image when running `PoseLandmarker`.
=> fix(sample): stop rotating the input image when running PoseLandmarker

Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/ResourceManager.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/ResourceManager/AssetBundleResourceManager.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/ResourceManager/LocalResourceManager.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/ResourceManager/StreamingAssetsResourceManager.cs
Caused by #1210.
Currently, when the sample graph or task runner is rerun (e.g. after changing the config), it fails because the dependent resources is already prepared.
This PR fixes this issue by always overwriting the internal `Dictionary`.
=> fix: fail to rerun the sample graph

Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/FaceLandmarker/FaceLandmarker.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/HandLandmarker/HandLandmarker.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/ImageSegmenter/ImageSegmenter.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/PoseLandmarker/PoseLandmarker.cs
For now, the input `Image` isn't released immediately even if it cannot be reached anymore.
=> fix: dispose callback arguments immediately

docker/linux/x86_64/Dockerfile
Avoid hermetic python version errors.
cf. https://github.com/homuler/MediaPipeUnityPlugin/actions/runs/12610418764
```txt
Could not find requirements_lock.txt file matching specified Python version.
Specified python version: 3.8
```
=> fix: avoid HERMETIC_PYTHON_VERSION errors

Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Components/Containers/ClassificationResult.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Components/Containers/Landmark.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Components/Containers/ListExtension.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Components/Containers/ListExtension.cs.meta, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Components/Containers/NativeArrayExtension.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Components/Containers/NativeArrayExtension.cs.meta, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/FaceLandmarker/FaceLandmarkerResult.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/HandLandmarker/HandLandmarkerResult.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/PoseLandmarker/PoseLandmarkerResult.cs
related to #1223 
Currently, when the task runner is in LIVE_STREAM mode, some data (e.g. Landmark.landmarks) is not deep copied correctly.
=> fix: deep clone result to avoid data race

Assets/MediaPipeUnity/Samples/Scenes/Image Segmentation/ImageSegmenterRunner.cs, Assets/MediaPipeUnity/Samples/Scenes/Pose Landmark Detection/PoseLandmarkerRunner.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/ImageSegmenter/ImageSegmenterResult.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/ImageSegmenterResultAnnotationController.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/PoseLandmarkerResultAnnotationController.cs
Currently, when drawing a segmentation mask for annotation, data is not read immediately, so the AnnotationController manages the lifecycle of the mask. Depending on how the code is written, this can easily lead to crashes.
In this PR, we changed the process to read the segmentation mask immediately, allowing the mask to be disposed of without relying on the AnnotationController.
=> fix: read masks immediately to avoid crash and memory leaks

Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Components/Containers/ClassificationResult.cs
caused by #1302 
Fixed an issue where categories were mistakenly cleared when copying them.
=> fix: copy categories correctly

Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Components/Containers/DetectionResult.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Components/Containers/ListExtension.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/DetectionResultAnnotationController.cs
Fix an issue with DetectionResult, similar to #1305.
=> fix: acquire a lock when drawing DetectionResult annotations

Assets/MediaPipeUnity/Samples/Scenes/Face Detection/FaceDetectorRunner.cs, Assets/MediaPipeUnity/Samples/Scenes/Face Landmark Detection/FaceLandmarkerRunner.cs, Assets/MediaPipeUnity/Samples/Scenes/Hand Landmark Detection/HandLandmarkerRunner.cs, Assets/MediaPipeUnity/Samples/Scenes/Image Segmentation/ImageSegmenterRunner.cs, Assets/MediaPipeUnity/Samples/Scenes/Object Detection/ObjectDetectorRunner.cs, Assets/MediaPipeUnity/Samples/Scenes/Pose Landmark Detection/PoseLandmarkerRunner.cs
Potential fix for https://github.com/homuler/MediaPipeUnityPlugin/issues/1238 
I've only implemented this for the `FaceLandmarkerRunner` for now because I wanted to get your thoughts on it first.
---
I've noticed that on my Samsung S21 when using `ImageReadMode.GPU`, the video would "glitch" in a weird way. The detected landmarks would look like they jumped back in time a few frames randomly from time to time, which is also what's visible in the slo-mo video from https://github.com/homuler/MediaPipeUnityPlugin/issues/1238 . It gets especially bad when I turn on `Multithreaded Rendering` in the Android build settings.
After some digging, I believe this is because the GPU operations that copy the frame data to the `TextureFrame` texture aren't guaranteed to finish before sending it off to …
=> Resolve landmark jitter by adjusting frame copy timing

Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/HolisticLandmarker/HolisticLandmarker.cs
For now, HolisticLandmarker does not support `imageProcessingOptions`, so remove the corresponding argument.
=> refactor: remove unused image processing options

Assets/MediaPipeUnity/Samples/Scenes/Legacy/Holistic/HolisticTrackingSolution.cs, Assets/MediaPipeUnity/Samples/Scenes/Legacy/MediaPipe Video/MediaPipeVideoSolution.cs, Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Experimental/TextureFrame.cs
Thank you for this nice plugin!
I found a memory leak problem and it cause runtime crash on iPhone.
It happens when I repeat Instantiate and Destroy components (ex. Holistic solution) via my script.
In memory profiler, Texture2D was increasing and leaking,
and those textures seem to have been generated by TextureFrames.
After adding Destroy() in `Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Experimental/TextureFrame.cs`, it's fixed.
I confirmed about `Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Experimental/TextureFrame.cs`, but I don't know how should I do about `Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/TextureFrame.cs`.
This Pull Request is just for your information.
=> fix: Destroy textures to fix memory leak

Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/FaceLandmarker/FaceLandmarkerResult.cs
Fix #1354 , by the approach referred in the bottom of the issue description.
After the fix, the rotation will be continuous.
https://github.com/user-attachments/assets/3a9022e0-50db-4afd-b82d-28912e9e1b24
Even after the fix, there is a case that the rotation's XZ component in eulerAngle must be negated to show spatially correct result.
So far I am not going to fix this behavior in the PR, since it is not serious as original issue.
=> Fix coordinate transformation process in FaceLandmarker

WORKSPACE, third_party/zlib.patch
This fix is not correct (may break build for those who are using an older Xcode), but at least we can avoid errors on our CI environment. 
cf. https://github.com/google-ai-edge/mediapipe/issues/5943
=> fix: workaround for compilation errors on macOS
