homuler/MediaPipeUnityPlugin

- README.md
- WORKSPACE
- Migrate Installation Guide to Wiki
- Add Hello World! sample code
- Comment out `api_level` for `android_ndk_repository` by default
> doc: revamp README

- Assets/Mediapipe/Samples/Scenes/Holistic/holistic_cpu.txt
- Assets/Mediapipe/Samples/Scenes/Holistic/holistic_gpu.txt
- Assets/Mediapipe/Samples/Scenes/Holistic/holistic_opengles.txt
- Assets/Mediapipe/Samples/Scenes/Pose Tracking/pose_tracking_cpu.txt
- Assets/Mediapipe/Samples/Scenes/Pose Tracking/pose_tracking_gpu.txt
- Assets/Mediapipe/Samples/Scenes/Pose Tracking/pose_tracking_opengles.txt
> fix(sample): smooth_landmarks option is not working

- Assets/Mediapipe/Samples/Common/Scripts/ImageSource/TextureFrame.cs
> fix: memory for RenderTexture leaks

- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Gpu/GlCalculatorHelper.cs
> fix: no need to pin callbacks

- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/StringPacket.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Port/StatusOrString.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Port/StatusOrString.cs.meta
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/ValidatedGraphConfig.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/ValidatedGraphConfig.cs.meta
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/PInvoke/NativeMethods/External/Stdlib_Safe.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/PInvoke/NativeMethods/External/Stdlib_Safe.cs.meta
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/PInvoke/NativeMethods/External/Stdlib_Unsafe.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/PInvoke/NativeMethods/Framework/Packet_Unsafe.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/PInvoke/NativeMethods/Framework/ValidatedGraphConfig_Safe.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/PInvoke/NativeMethods/Framework/ValidatedGraphConfig_Safe.cs.meta
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/PInvoke/NativeMethods/Framework/ValidatedGraphConfig_Unsafe.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/PInvoke/NativeMethods/Framework/ValidatedGraphConfig_Unsafe.cs.meta
- Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Packet/StringPacketTest.cs
- Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Port/StatusOrStringTest.cs
- Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Port/StatusOrStringTest.cs.meta
- Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/ValidatedGraphConfigTest.cs
- Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/ValidatedGraphConfigTest.cs.meta
- mediapipe_api/BUILD
- mediapipe_api/external/BUILD
- mediapipe_api/external/stdlib.cc
- mediapipe_api/external/stdlib.h
- mediapipe_api/framework/BUILD
- mediapipe_api/framework/packet.cc
- mediapipe_api/framework/packet.h
- mediapipe_api/framework/validated_graph_config.cc
- mediapipe_api/framework/validated_graph_config.h
> feat(plugin): port ValidatedGraphConfig API

- Assets/Mediapipe/Samples/Common/Scripts/Screen.cs
In some cases, the screen image is not rotated properly when using a front camera.
> fix(sample): front camera image is not rotated properly

- Assets/Mediapipe/Samples/Scenes/Hair Segmentation/Hair Segmentation.unity
- Assets/Mediapipe/Samples/Scenes/Hair Segmentation/HairSegmentationGraph.cs
- Assets/Mediapipe/Samples/Scenes/Hair Segmentation/hair_segmentation_cpu.txt
- Assets/Mediapipe/Samples/Scenes/Hair Segmentation/hair_segmentation_gpu.txt
- Assets/Mediapipe/Samples/Scenes/Hair Segmentation/hair_segmentation_opengles.txt
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Formats/ImageFrame.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/PInvoke/NativeMethods/Framework/Format/ImageFrame_Safe.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/MaskAnnotation.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/MaskAnnotationController.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Extension/ImageFrameExtension.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Extension/ImageFrameExtension.cs.meta
- Packages/com.github.homuler.mediapipe/Runtime/Shaders/Convergence Shader.shader
- Packages/com.github.homuler.mediapipe/Runtime/Shaders/MaskShader.shader
- Packages/com.github.homuler.mediapipe/Runtime/Shaders/MaskShader.shader.meta
- Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Format/ImageFrameTest.cs
- Packages/com.github.homuler.mediapipe/Tests/EditMode/Unity/Extension.meta
- Packages/com.github.homuler.mediapipe/Tests/EditMode/Unity/Extension/ImageFrameExtensionTest.cs
- Packages/com.github.homuler.mediapipe/Tests/EditMode/Unity/Extension/ImageFrameExtensionTest.cs.meta
- mediapipe_api/framework/formats/image_frame.cc
- mediapipe_api/framework/formats/image_frame.h
related to #195.
- (BREAKING) implement `ImageFrame#TryReadChannel` and remove `ImageFrame#GetChannel`
- (BREAKING) render annotations using `MaskShader` in the Hair Segmentation scene
> perf!: implement ImageFrame#TryReadChannel and MaskShader

- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Formats/ImageFrame.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Extension/ImageFrameExtension.cs
- Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Format/ImageFrameTest.cs
- Packages/com.github.homuler.mediapipe/Tests/EditMode/Unity/Extension/ImageFrameExtensionTest.cs
- (BREAKING) modify I/F of `ImageFrame#CopyToBuffer`
- (BREAKING) remove `ImageFrame#GetPixels32`
- implement `ImageFrame#TryReadPixelData`
> refactor!(plugin): reimplement ImageFrame extension methods

- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/Packet.cs
- Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Packet/BoolPacketTest.cs
- Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Packet/FloatArrayPacketTest.cs
- Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Packet/FloatPacketTest.cs
- Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Packet/ImageFramePacketTest.cs
- Packages/com.github.homuler.mediapipe/Tests/EditMode/Framework/Packet/StringPacketTest.cs
Revert a breaking change introduced by #509
> revert a breaking change

- Assets/Mediapipe/Samples/Scenes/Hair Segmentation/HairSegmentationSolution.cs
- Assets/Mediapipe/Samples/Scenes/Pose Tracking/Pose Tracking Config Window.prefab
- Assets/Mediapipe/Samples/Scenes/Pose Tracking/Pose Tracking.unity
- Assets/Mediapipe/Samples/Scenes/Pose Tracking/PoseTrackingConfig.cs
- Assets/Mediapipe/Samples/Scenes/Pose Tracking/PoseTrackingGraph.cs
- Assets/Mediapipe/Samples/Scenes/Pose Tracking/PoseTrackingSolution.cs
- Assets/Mediapipe/Samples/Scenes/Pose Tracking/pose_tracking_cpu.txt
- Assets/Mediapipe/Samples/Scenes/Pose Tracking/pose_tracking_gpu.txt
- Assets/Mediapipe/Samples/Scenes/Pose Tracking/pose_tracking_opengles.txt
- Packages/com.github.homuler.mediapipe/Runtime/Objects/Mask Annotation.prefab
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/MaskAnnotation.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/MaskAnnotationController.cs
- Packages/com.github.homuler.mediapipe/Runtime/Shaders/MaskShader.shader
- Packages/com.github.homuler.mediapipe/Runtime/Shaders/UnmaskShader.shader
- Packages/com.github.homuler.mediapipe/Runtime/Shaders/UnmaskShader.shader.meta
related to #291 
Support `enable_segmentation` and `smooth_segmentation` in the Pose Scene.
> feat(sample): Pose Segmentation Mask

- Assets/Mediapipe/Samples/Scenes/Hello World/HelloWorldConfig.cs
- Assets/Mediapipe/Samples/Scenes/Holistic/Holistic Tracking Config Window.prefab
- Assets/Mediapipe/Samples/Scenes/Holistic/Holistic.unity
- Assets/Mediapipe/Samples/Scenes/Holistic/HolisticTrackingConfig.cs
- Assets/Mediapipe/Samples/Scenes/Holistic/HolisticTrackingGraph.cs
- Assets/Mediapipe/Samples/Scenes/Holistic/HolisticTrackingSolution.cs
- Assets/Mediapipe/Samples/Scenes/Holistic/holistic_cpu.txt
- Assets/Mediapipe/Samples/Scenes/Holistic/holistic_gpu.txt
- Assets/Mediapipe/Samples/Scenes/Holistic/holistic_opengles.txt
- Assets/Mediapipe/Samples/Scenes/Pose Tracking/Pose Tracking.unity
- Assets/Mediapipe/Samples/Scenes/Pose Tracking/pose_tracking_cpu.txt
- Assets/Mediapipe/Samples/Scenes/Pose Tracking/pose_tracking_gpu.txt
- Assets/Mediapipe/Samples/Scenes/Pose Tracking/pose_tracking_opengles.txt
close #291 
Support segmentation mask in the Holistic Scene.
> feat(sample): Holistic Segmentation Mask

- Assets/Mediapipe/Samples/Scenes/Selfie Segmentation.meta
- Assets/Mediapipe/Samples/Scenes/Selfie Segmentation/Selfie Segmentation Config Window.prefab
- Assets/Mediapipe/Samples/Scenes/Selfie Segmentation/Selfie Segmentation Config Window.prefab.meta
- Assets/Mediapipe/Samples/Scenes/Selfie Segmentation/Selfie Segmentation.unity
- Assets/Mediapipe/Samples/Scenes/Selfie Segmentation/Selfie Segmentation.unity.meta
- Assets/Mediapipe/Samples/Scenes/Selfie Segmentation/SelfieSegmentationConfig.cs
- Assets/Mediapipe/Samples/Scenes/Selfie Segmentation/SelfieSegmentationConfig.cs.meta
- Assets/Mediapipe/Samples/Scenes/Selfie Segmentation/SelfieSegmentationGraph.cs
- Assets/Mediapipe/Samples/Scenes/Selfie Segmentation/SelfieSegmentationGraph.cs.meta
- Assets/Mediapipe/Samples/Scenes/Selfie Segmentation/SelfieSegmentationSolution.cs
- Assets/Mediapipe/Samples/Scenes/Selfie Segmentation/SelfieSegmentationSolution.cs.meta
- Assets/Mediapipe/Samples/Scenes/Selfie Segmentation/selfie_segmentation_cpu.txt
- Assets/Mediapipe/Samples/Scenes/Selfie Segmentation/selfie_segmentation_cpu.txt.meta
- Assets/Mediapipe/Samples/Scenes/Selfie Segmentation/selfie_segmentation_gpu.txt
- Assets/Mediapipe/Samples/Scenes/Selfie Segmentation/selfie_segmentation_gpu.txt.meta
- Assets/Mediapipe/Samples/Scenes/Selfie Segmentation/selfie_segmentation_opengles.txt
- Assets/Mediapipe/Samples/Scenes/Selfie Segmentation/selfie_segmentation_opengles.txt.meta
- Packages/com.github.homuler.mediapipe/Runtime/Resources/selfie_segmentation.bytes.meta
- ProjectSettings/EditorBuildSettings.asset
- README.md
- mediapipe_api/BUILD
> feat(sample): Selfie Segmentation

- Assets/Mediapipe/Samples/Scenes/Face Detection/Face Detection Config Window.prefab
- Assets/Mediapipe/Samples/Scenes/Face Detection/FaceDetectionConfig.cs
- Assets/Mediapipe/Samples/Scenes/Face Detection/FaceDetectionGraph.cs
- Assets/Mediapipe/Samples/Scenes/Face Detection/FaceDetectionSolution.cs
- Assets/Mediapipe/Samples/Scenes/Face Mesh/Face Mesh Config Window.prefab
- Assets/Mediapipe/Samples/Scenes/Face Mesh/FaceMeshConfig.cs
- Assets/Mediapipe/Samples/Scenes/Face Mesh/FaceMeshGraph.cs
- Assets/Mediapipe/Samples/Scenes/Face Mesh/FaceMeshSolution.cs
- Assets/Mediapipe/Samples/Scenes/Hand Tracking/Hand Tracking Config Window.prefab
- Assets/Mediapipe/Samples/Scenes/Hand Tracking/HandTrackingConfig.cs
- Assets/Mediapipe/Samples/Scenes/Hand Tracking/HandTrackingGraph.cs
- Assets/Mediapipe/Samples/Scenes/Hand Tracking/HandTrackingSolution.cs
- Assets/Mediapipe/Samples/Scenes/Holistic/Holistic Tracking Config Window.prefab
- Assets/Mediapipe/Samples/Scenes/Holistic/HolisticTrackingConfig.cs
- Assets/Mediapipe/Samples/Scenes/Holistic/HolisticTrackingGraph.cs
- Assets/Mediapipe/Samples/Scenes/Holistic/HolisticTrackingSolution.cs
- Assets/Mediapipe/Samples/Scenes/Pose Tracking/Pose Tracking Config Window.prefab
- Assets/Mediapipe/Samples/Scenes/Pose Tracking/PoseTrackingConfig.cs
- Assets/Mediapipe/Samples/Scenes/Pose Tracking/PoseTrackingGraph.cs
- Assets/Mediapipe/Samples/Scenes/Pose Tracking/PoseTrackingSolution.cs
- packages.config
> feat(sample): MIN_DETECTION_CONFIDENCE and MIN_TRACKING_CONFIDENCE

- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Formats/ImageFrame.cs
- Add `ImageFrame` constructors to give more flexibility.
- Fix comments (the `pixelData` is not moved)
> feat: initialize ImageFrame with a pointer to pixel data

- Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/StaticImageSource.cs
- Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/VideoSource.cs
> fix(sample): the default video/image is not selected

- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/Anchor3dVectorPacket.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/BoolPacket.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/ClassificationListPacket.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/ClassificationListVectorPacket.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/DetectionPacket.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/DetectionVectorPacket.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/FaceGeometryPacket.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/FaceGeometryVectorPacket.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/FloatArrayPacket.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/FloatPacket.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/FrameAnnotationPacket.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/GpuBufferPacket.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/ImageFramePacket.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/IntPacket.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/LandmarkListPacket.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/LandmarkListVectorPacket.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/NormalizedLandmarkListPacket.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/NormalizedLandmarkListVectorPacket.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/NormalizedRectPacket.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/NormalizedRectVectorPacket.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/RectPacket.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/RectVectorPacket.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/StringPacket.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Packet/TimedModelMatrixProtoListPacket.cs
> fix(plugin): preserve Packet constructors for Reflection

- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/ResourceManager/LocalResourceManager.cs
> fix(plugin): check if the target local asset is missing

- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/GlobalInstanceTable.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/OutputStream.cs
> fix(plugin): prevent Status returned by a packet callback from being GCed prematurely

- Assets/MediaPipeUnity/Samples/Scenes/Box Tracking/BoxTrackingGraph.cs
- Assets/MediaPipeUnity/Samples/Scenes/Face Detection/FaceDetectionGraph.cs
- Assets/MediaPipeUnity/Samples/Scenes/Face Mesh/FaceMeshGraph.cs
- Assets/MediaPipeUnity/Samples/Scenes/Hair Segmentation/HairSegmentationGraph.cs
- Assets/MediaPipeUnity/Samples/Scenes/Hand Tracking/HandTrackingGraph.cs
- Assets/MediaPipeUnity/Samples/Scenes/Holistic/HolisticTrackingGraph.cs
- Assets/MediaPipeUnity/Samples/Scenes/Instant Motion Tracking/RegionTrackingGraph.cs
- Assets/MediaPipeUnity/Samples/Scenes/Iris Tracking/IrisTrackingGraph.cs
- Assets/MediaPipeUnity/Samples/Scenes/MediaPipe Video/MediaPipeVideoGraph.cs
- Assets/MediaPipeUnity/Samples/Scenes/Object Detection/ObjectDetectionGraph.cs
- Assets/MediaPipeUnity/Samples/Scenes/Objectron/ObjectronGraph.cs
- Assets/MediaPipeUnity/Samples/Scenes/Pose Tracking/PoseTrackingGraph.cs
- Assets/MediaPipeUnity/Samples/Scenes/Selfie Segmentation/SelfieSegmentationGraph.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/OutputStream.cs
> fix(sample): dispose OutputStream if only it exists

- Assets/MediaPipeUnity/Samples/Common/Scripts/Bootstrap.cs
- Assets/MediaPipeUnity/Samples/UI/Scripts/GUIConsole.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Logger.cs
Renames `Logger` members to follow the naming conventions.
> refactor(plugin)!: Logger.minLogLevel -> Logger.MinLogLevel

- Assets/MediaPipeUnity/Editor/PackageExporter.cs
- Assets/MediaPipeUnity/Tutorial.meta
- Assets/MediaPipeUnity/Tutorial/Hello World.meta
- Assets/MediaPipeUnity/Tutorial/Hello World/Hello World.unity
- Assets/MediaPipeUnity/Tutorial/Hello World/Hello World.unity.meta
- Assets/MediaPipeUnity/Tutorial/Hello World/HelloWorld.cs
- Assets/MediaPipeUnity/Tutorial/Hello World/HelloWorld.cs.meta
- Assets/MediaPipeUnity/Tutorial/Official Solution.meta
- Assets/MediaPipeUnity/Tutorial/Official Solution/FaceMesh.cs
- Assets/MediaPipeUnity/Tutorial/Official Solution/FaceMesh.cs.meta
- Assets/MediaPipeUnity/Tutorial/Official Solution/Official Solution.unity
- Assets/MediaPipeUnity/Tutorial/Official Solution/Official Solution.unity.meta
- Assets/MediaPipeUnity/Tutorial/Official Solution/face_mesh_desktop_live.txt
- Assets/MediaPipeUnity/Tutorial/Official Solution/face_mesh_desktop_live.txt.meta
- Assets/MediaPipeUnity/Tutorial/Official Solution/face_mesh_desktop_live_gpu.txt
- Assets/MediaPipeUnity/Tutorial/Official Solution/face_mesh_desktop_live_gpu.txt.meta
- Packages/com.github.homuler.mediapipe/package.json
Adds sample scenes for [this tutorial](https://github.com/homuler/MediaPipeUnityPlugin/wiki/Getting-Started#tutorial).
> feat: add scenes for tutorial

- WORKSPACE
> fix: OpenCV paths os macOS

- Assets/MediaPipeUnity/Samples/Scenes/Objectron/Objectron Config Window.prefab
- Assets/MediaPipeUnity/Samples/Scenes/Objectron/ObjectronConfig.cs
- Assets/MediaPipeUnity/Samples/Scenes/Objectron/ObjectronGraph.cs
- Assets/MediaPipeUnity/Samples/Scenes/Objectron/ObjectronSolution.cs
- Assets/MediaPipeUnity/Samples/UI/Objects/Console/Console.prefab
- Packages/com.github.homuler.mediapipe/Runtime/Objects/Arrow.prefab
- Packages/com.github.homuler.mediapipe/Runtime/Objects/Circle Annotation.prefab
- Packages/com.github.homuler.mediapipe/Runtime/Objects/Connection Annotation.prefab
- Packages/com.github.homuler.mediapipe/Runtime/Objects/Cuboid Annotation.prefab
- Packages/com.github.homuler.mediapipe/Runtime/Objects/Rectangle Annotation.prefab
- Packages/com.github.homuler.mediapipe/Runtime/Objects/Transform Annotation.prefab
> feat(objectron): set confidence parameters at runtime

- Assets/MediaPipeUnity/Samples/Scenes/Hand Tracking/HandTrackingGraph.cs
- Packages/com.github.homuler.mediapipe/Runtime/Objects/Detection Annotation.prefab
- Packages/com.github.homuler.mediapipe/Runtime/Objects/FaceLandmarkListWithIris Annotation.prefab
- Packages/com.github.homuler.mediapipe/Runtime/Objects/HolisticLandmarkList Annotation.prefab
- build.py
- mediapipe_api/BUILD
Implement the `--solutions` option.
Now we can build libraries with only required solutions.
```sh
python build.py build --desktop gpu --opencv cmake --solutions face_mesh hands pose -vv
```
> build: select required solutions when building libraries

- WORKSPACE
- build.py
- mediapipe_api/BUILD
- third_party/build_bazel_apple_support_transitions.diff
- third_party/opencv.BUILD
- third_party/opencv_disable_neon.diff
This PR enables us to build the universal library on M1 Mac and Intel Mac.
closes #611.
> build: Universal macOS Library

- .github/workflows/linux-test.yml
- .github/workflows/macos-test.yml
- .github/workflows/run-tests.yml
- .github/workflows/windows-test.yml
- Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.dylib.meta
- Packages/com.github.homuler.mediapipe/package.json
> ci: run tests with GitHub Actions

- Assets/MediaPipeUnity/Samples/Common/Scripts/ImageSource/WebCamSource.cs
handle timeout issue #664
change timeoutFrame value from 500 to 2000
> increase timeoutFrame for waiting WebCam

- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/OutputStream.cs
fix https://github.com/homuler/MediaPipeUnityPlugin/issues/682#issuecomment-1215124791.
> docs: improve the OutputStream Not Found error message

- Packages/com.github.homuler.mediapipe/Runtime/Shaders/UnmaskShader.shader
> feat: make mask color transparent

- .github/workflows/build-package.yml
- .github/workflows/package.yml
- .github/workflows/release-packages.yml
> ci: build the release package with symbols stripped

- .github/workflows/linux-test.yml
- .github/workflows/macos-test.yml
- .github/workflows/package.yml
- .github/workflows/windows-test.yml
- cat `results.xml` if the test failed
- print `inputs` for `package.yml`
- remove temporary packages after running tests
> ci: improve readability of test results

- .github/workflows/linux-test.yml
- .github/workflows/macos-test.yml
- .github/workflows/windows-test.yml
CI is failing because it can't handle the ToS popup.
> ci: install the latest unity-license-activate

- .github/workflows/package.yml
- Assets/MediaPipeUnity/Editor/PackageExporter.cs
- Packages/com.github.homuler.mediapipe/package.json
- Export the Start Scene
- Export all the project files as a zip
- Export unitypackage
> ci: export all the project files

- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/Arrow.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/CircleAnnotation.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/ConnectionListAnnotation.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/CuboidListAnnotation.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/DetectionListAnnotation.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/LineAnnotation.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/MaskAnnotation.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/MultiFaceLandmarkListAnnotation.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/MultiHandLandmarkListAnnotation.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/PointListAnnotation.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/PoseLandmarkListAnnotation.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/RectangleAnnotation.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/RectangleListAnnotation.cs
> fix: stop running OnValidate on immutable prefabs

- Assets/MediaPipeUnity/Editor/PackageExporter.cs
> fix: include MediaPipeUnity.framework in unitypackage

- Packages/com.github.homuler.mediapipe/Runtime/Scripts/PInvoke/NativeMethods/Tasks/TaskRunner_Unsafe.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Core/PacketsCallbackTable.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Core/PacketsCallbackTable.cs.meta
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Core/TaskRunner.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/Core/BaseVisionTaskApi.cs
- Packages/com.github.homuler.mediapipe/Tests/EditMode/Tasks/Core/TaskRunnerTest.cs
- mediapipe_api/tasks/cc/core/task_runner.cc
- mediapipe_api/tasks/cc/core/task_runner.h
- implement PacketsCallbackTable
- NativePacketsCallback will be called with the callback_id now
- Process / Send dispose PacketMap
> feat: implement PacketsCallbackTable

- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Experimental/TextureFrame.cs
- fix MissingReferenceException
- determine the graphicsFormat at runtime
> fix: determine the GrahpicsFormat at runtime

- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/ConnectionListAnnotation.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/DetectionListAnnotation.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/DetectionListAnnotationController.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/FaceLandmarkListAnnotation.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/FaceLandmarkListAnnotationController.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/FaceLandmarkListWithIrisAnnotation.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/HandLandmarkListAnnotation.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/HolisticLandmarkListAnnotation.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/HolisticLandmarkListAnnotationController.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/IrisLandmarkListAnnotation.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/ListAnnotation.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/MultiFaceLandmarkListAnnotation.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/MultiFaceLandmarkListAnnotationController.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/MultiHandLandmarkListAnnotation.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/MultiHandLandmarkListAnnotationController.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/NormalizedLandmarkListAnnotationController.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/NormalizedRectListAnnotationController.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/PointListAnnotation.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/PoseLandmarkListAnnotation.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/PoseLandmarkListAnnotationController.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/PoseWorldLandmarkListAnnotationController.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/RectangleListAnnotation.cs
> refactor: use IReadOnlyList as arguments for annotations

- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Protobuf/Tasks/Vision/FaceLandmarker.meta
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Protobuf/Tasks/Vision/FaceLandmarker/Proto.meta
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Protobuf/Tasks/Vision/FaceLandmarker/Proto/FaceBlendshapesGraphOptions.cs.meta
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Protobuf/Tasks/Vision/FaceLandmarker/Proto/FaceLandmarkerGraphOptions.cs.meta
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Protobuf/Tasks/Vision/FaceLandmarker/Proto/FaceLandmarksDetectorGraphOptions.cs.meta
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/FaceLandmarker.meta
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/FaceLandmarker/FaceLandmarker.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/FaceLandmarker/FaceLandmarker.cs.meta
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/FaceLandmarker/FaceLandmarkerOptions.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/FaceLandmarker/FaceLandmarkerOptions.cs.meta
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/FaceLandmarker/FaceLandmarkerResult.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/FaceLandmarker/FaceLandmarkerResult.cs.meta
- mediapipe_api/BUILD
- mediapipe_api/tasks/cc/vision/face_landmarker/proto/BUILD
- third_party/mediapipe_visibility.diff
closes #787 , closes #795 , closes #802 , closes #862 , closes #909 , closes #945 , closes #961
> feat: implement FaceLandmarker

- Packages/com.github.homuler.mediapipe/Runtime/Scripts/PInvoke/NativeMethods/Framework/Format/Image_Safe.cs
Fixed the issue of incorrectly obtaining the address of the pointer of Image pixel data.
> fix: obtain the pointer of Image pixel data correctly

- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Core/PacketsCallbackTable.cs
Add a profiler marker to profile method calls from a thread other than the Main Thread.
> refactor: add a profiler marker for NativePacketsCallback

- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Components/Containers/Landmark.cs
> fix: all landmarks except the last one are always null

- Assets/MediaPipeUnity/Samples/Common/Scripts/GraphRunner.cs
> fix(sample): Android build error

- Assets/MediaPipeUnity/Samples/Scenes/Face Detection/FaceDetectorRunner.cs
- Assets/MediaPipeUnity/Samples/Scenes/Face Landmark Detection/FaceLandmarkerRunner.cs
- Assets/MediaPipeUnity/Samples/Scenes/Hand Landmark Detection/HandLandmarkerRunner.cs
- Assets/MediaPipeUnity/Samples/Scenes/Image Segmentation/ImageSegmenterRunner.cs
- Assets/MediaPipeUnity/Samples/Scenes/Object Detection/ObjectDetectorRunner.cs
- Assets/MediaPipeUnity/Samples/Scenes/Pose Landmark Detection/PoseLandmarkerRunner.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/PInvoke/NativeMethods/Tasks/TaskRunner_Unsafe.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Core/TaskRunner.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/Core/BaseVisionTaskApi.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/FaceDetector/FaceDetector.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/FaceGeometry.meta
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/FaceLandmarker/FaceLandmarker.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/HandLandmarker/HandLandmarker.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/ImageSegmenter/ImageSegmenter.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/ObjectDetector/ObjectDetector.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Vision/PoseLandmarker/PoseLandmarker.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Experimental/TextureFrame.cs
- mediapipe_api/tasks/cc/core/task_runner.cc
- mediapipe_api/tasks/cc/core/task_runner.h
> feat: Task API with GPU Image

- .github/workflows/macos-test.yml
- .github/workflows/package.yml
> build!: build libs on macos-13 image

- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Framework/Formats/Image.cs
Fixed a typo that broke Linux builds.
> fix: build failure on Linux

- build.py
> build: disable bitcode since it's deprecated

- Assets/MediaPipeUnity/Samples/Scenes/Face Detection/FaceDetectorRunner.cs
- Assets/MediaPipeUnity/Samples/Scenes/Face Landmark Detection/FaceLandmarkerRunner.cs
- Assets/MediaPipeUnity/Samples/Scenes/Hand Landmark Detection/HandLandmarkerRunner.cs
- Assets/MediaPipeUnity/Samples/Scenes/Image Segmentation/ImageSegmenterRunner.cs
- Assets/MediaPipeUnity/Samples/Scenes/Legacy/Holistic/HolisticTrackingSolution.cs
- Assets/MediaPipeUnity/Samples/Scenes/Legacy/MediaPipe Video/MediaPipeVideoSolution.cs
- Assets/MediaPipeUnity/Samples/Scenes/Object Detection/ObjectDetectorRunner.cs
- Assets/MediaPipeUnity/Samples/Scenes/Pose Landmark Detection/PoseLandmarkerRunner.cs
> fix: keep running CalculatorGraph if another window takes focus

- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/FaceLandmarkerResultAnnotationController.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Annotation/HandLandmarkerResultAnnotationController.cs
> fix: acquire a lock when drawing annotations

- Assets/MediaPipeUnity/Samples/Common/Scripts/ImageReadMode.cs
- Assets/MediaPipeUnity/Samples/Common/Scripts/ImageReadMode.cs.meta
- Assets/MediaPipeUnity/Samples/Scenes/Face Detection/Face Detection Config Window.prefab
- Assets/MediaPipeUnity/Samples/Scenes/Face Detection/FaceDetectionConfig.cs
- Assets/MediaPipeUnity/Samples/Scenes/Face Detection/FaceDetectionConfigWindow.cs
- Assets/MediaPipeUnity/Samples/Scenes/Face Detection/FaceDetectorRunner.cs
- Assets/MediaPipeUnity/Samples/Scenes/Face Landmark Detection/Face Landmark Detection Config Window.prefab
- Assets/MediaPipeUnity/Samples/Scenes/Face Landmark Detection/FaceLandmarkDetectionConfig.cs
- Assets/MediaPipeUnity/Samples/Scenes/Face Landmark Detection/FaceLandmarkDetectionConfigWindow.cs
- Assets/MediaPipeUnity/Samples/Scenes/Face Landmark Detection/FaceLandmarkerRunner.cs
- Assets/MediaPipeUnity/Samples/Scenes/Hand Landmark Detection/Hand Landmark Detection Config Window.prefab
- Assets/MediaPipeUnity/Samples/Scenes/Hand Landmark Detection/HandLandmarkDetectionConfig.cs
- Assets/MediaPipeUnity/Samples/Scenes/Hand Landmark Detection/HandLandmarkDetectionConfigWindow.cs
- Assets/MediaPipeUnity/Samples/Scenes/Hand Landmark Detection/HandLandmarkerRunner.cs
- Assets/MediaPipeUnity/Samples/Scenes/Image Segmentation/Image Segmentation Config Window.prefab
- Assets/MediaPipeUnity/Samples/Scenes/Image Segmentation/ImageSegmentationConfig.cs
- Assets/MediaPipeUnity/Samples/Scenes/Image Segmentation/ImageSegmentationConfigWindow.cs
- Assets/MediaPipeUnity/Samples/Scenes/Image Segmentation/ImageSegmenterRunner.cs
- Assets/MediaPipeUnity/Samples/Scenes/Legacy/MediaPipe Video/MediaPipeVideoSolution.cs
- Assets/MediaPipeUnity/Samples/Scenes/Object Detection/Object Detection Config Window.prefab
- Assets/MediaPipeUnity/Samples/Scenes/Object Detection/ObjectDetectionConfig.cs
- Assets/MediaPipeUnity/Samples/Scenes/Object Detection/ObjectDetectionConfigWindows.cs
- Assets/MediaPipeUnity/Samples/Scenes/Object Detection/ObjectDetectorRunner.cs
- Assets/MediaPipeUnity/Samples/Scenes/Pose Landmark Detection/Pose Landmark Detection Config Window.prefab
- Assets/MediaPipeUnity/Samples/Scenes/Pose Landmark Detection/PoseLandmarkDetectionConfig.cs
- Assets/MediaPipeUnity/Samples/Scenes/Pose Landmark Detection/PoseLandmarkDetectionConfigWindow.cs
- Assets/MediaPipeUnity/Samples/Scenes/Pose Landmark Detection/PoseLandmarkerRunner.cs
- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Unity/Experimental/TextureFrame.cs
related to #1238.
Added a mode for reading input images, enabling dynamic adjustment to prioritize either latency or FPS.
> feat(sample): implement ImageReadMode

- Packages/com.github.homuler.mediapipe/Runtime/Scripts/Tasks/Core/BaseOptions.cs
related to #1296 
cf. https://github.com/google-ai-edge/mediapipe/commit/7d8d3ab1968c6146106805566f3163189c2b6409
> feat: support EDGETPU_NNAPI
